name: bellmanscafe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - flake8
  - nose
  - coverage >= 6  # to ensure lcov option is available
  - flask
  - markdown
  - imp-python3
