name: Check_Codestyle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python_codestyle:
    runs-on: ubuntu-latest

    steps:
    - name: update apt
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install python3 python3-pip

    # configure conda
    - name: Setup for conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
    - name: create conda env
      run: |
        conda config --add channels conda-forge
        conda config --add channels anaconda
        conda create -q --yes -n bellmanscafe python=3.9 flake8 markdown
        conda init bash
        source ~/.bashrc
        conda activate bellmanscafe
    - uses: actions/checkout@v2

    - name: codestyle check
      run: |
        conda init bash
        source ~/.bashrc
        conda activate bellmanscafe
        flake8

  python_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install pytest
      run: |
        pip install pytest-cov
    - name: install gapc
      run: |
        sudo add-apt-repository ppa:janssenlab/software
        sudo apt-get update
        sudo apt-get install bellmansgapc
    - name: Execute tests
      run: |
        cd bellmanscafe && pytest --cov=bellmanscafe --cov-report=lcov
    - name: Send coverage report to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "bellmanscafe/coverage.lcov"
