name: Check_Codestyle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python_codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install flake8
      run: |
            pip install flake8
    - name: codestyle check
      run: |
        flake8

  python_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install pytest
      run: |
        pip install pytest-cov markdown
    - name: install gapc
      run: |
        sudo add-apt-repository ppa:janssenlab/software
        sudo apt-get update
        sudo apt-get install bellmansgapc
    - name: Execute tests
      run: |
        cd bellmanscafe && pytest --cov=bellmanscafe --cov-report=lcov
    - name: Send coverage report to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "bellmanscafe/coverage.lcov"
